# Background color
screen.loading=23272A
# Loading bar background color
screen.loading.bar=23272A
# Loading bar outline color
screen.loading.outline=32383C
# Loading bar foreground color
screen.loading.progress=C29550
# Logo blending mode
screen.loading.blend=off